---
- name: Disable swap
  ansible.builtin.shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  changed_when: false

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true

- name: Allow Kubernetes API Server port in UFW
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "6443"
    - "2379:2380"
    - "10250"
    - "10259"
    - "10257"

- name: Allow Flannel VXLAN port in UFW
  community.general.ufw:
    rule: allow
    port: "8472"
    proto: udp

- name: Initialize the cluster
  ansible.builtin.command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeinit
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory for user
  ansible.builtin.file:
    path: "~{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Setup kubeconfig for user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "~{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Wait for Kubernetes API server to be ready
  ansible.builtin.wait_for:
    host: localhost
    port: 6443
    delay: 10
    timeout: 60

- name: Install Flannel CNI
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false

- name: Generate join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command_raw
  changed_when: false

- name: Set join command fact
  ansible.builtin.set_fact:
    join_command: "{{ join_command_raw.stdout }}"

- name: Install NGINX Ingress Controller
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/baremetal/deploy.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false

- name: Wait for NGINX Ingress Controller to be ready
  ansible.builtin.command:
    cmd: kubectl wait --for=condition=Available deployment/ingress-nginx-controller -n ingress-nginx --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false

- name: Wait for NGINX Ingress admission jobs to complete
  ansible.builtin.command:
    cmd: kubectl wait --for=condition=complete job --all -n ingress-nginx --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false

- name: Remove problematic NGINX admission webhook
  ansible.builtin.command:
    cmd: kubectl delete validatingwebhookconfigurations ingress-nginx-admission
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  failed_when: false # Don't fail if it's already deleted
  changed_when: true

- name: Patch NGINX Ingress Controller for hostNetwork
  ansible.builtin.command:
    cmd: >
      kubectl patch deployment ingress-nginx-controller -n ingress-nginx --type='json'
      -p='[{"op":"replace", "path":"/spec/template/spec/hostNetwork", "value":true}]'
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: true

- name: Untaint master node
  ansible.builtin.command:
    cmd: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  failed_when: false
  changed_when: true

- name: Force NGINX Ingress to run on Master node
  ansible.builtin.command:
    cmd: |
      kubectl patch deployment ingress-nginx-controller -n ingress-nginx --type='json' -p='[
        {"op":"add", "path":"/spec/template/spec/nodeSelector", "value":{"kubernetes.io/hostname":"master"}},
        {"op":"add", "path":"/spec/template/spec/tolerations",
        "value":[{"key":"node-role.kubernetes.io/control-plane", "operator":"Exists", "effect":"NoSchedule"}]}
      ]'
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: true

- name: Wait for all nodes to be ready
  ansible.builtin.command:
    cmd: kubectl wait --for=condition=Ready nodes --all --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false

- name: Install cert-manager
  ansible.builtin.command:
    cmd: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false

- name: Wait for cert-manager deployments to be ready
  ansible.builtin.command:
    cmd: kubectl wait --for=condition=Available --all deployments -n cert-manager --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false
